---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: rbac-sidecar
spec:
  serviceAccountName: rbac-sa
  containers:
    - name: rbac-main
      image: mhausenblas/simpleservice:0.5.0
      ports:
        - containerPort: 9876
    - name: rbac-side
      image: bpalmer/rbac-proxy-poc:latest
      ports:
        - containerPort: 8081
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: read-pods
subjects:
- kind: ServiceAccount
  name: rbac-sa
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbac-viewer
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "roles", "clusterrolebindings", "rolebindings"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-viewer-binding
subjects:
- kind: ServiceAccount
  name: rbac-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: rbac-viewer
  apiGroup: rbac.authorization.k8s.io
